export const HANDLE_POPUP_OPEN = "HANDLE_POPUP_OPEN";
export const HANDLE_POPUP_COMPONENT_RENDER = "HANDLE_POPUP_COMPONENT_RENDER";
export const SET_CONTRACT_DETAILS = "SET_CONTRACT_DETAILS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_MON_CARDS = "SET_MON_CARDS";
export const SET_NAVBAR_STATE = "SET_NAVBAR_STATE";
